var navData = {
    list:[
        //最近使用
        {
            title: "最近使用",
            icon: "history",
            nav: []
        },
		
		
        //实用工具
        {
            title: "实用工具",
            icon: "cog",
            child: [
                //图文编辑
                {
                    
                    title:"图文编辑",
                    nav:[
                        {
                            title:"百度脑图",
                            desc:"百度出品免费在线制作思维导图",
                            url:"https://naotu.baidu.com/",
                            image:"naotu.png"
                        }, 
                        {
                            title:"百度图说",
                            desc:"可视化制作图表(不需要会编程)作图表(不需要会编作图表(不需要会编爱你",
                            url:"https://tushuo.baidu.com/",
                            image:"tushuo.png"
                        }, 
                        {
                            title:"ZhiMap",
                            desc:"可多人同时编辑的免费在线思维导图",
                            url:"https://zhimap.com",
                            image:"zhimap.png"
                        }, 
                        {
                            title:"Diagrams",
                            desc:"【推荐】流程图免费制作",
                            url:"https://app.diagrams.net/",
                            image:"diagrams.png"
                        }, 
                        {
                            title:"石墨文档",
                            desc:"多人实时协办文档office",
                            url:"https://shimo.im",
                            image:"shimo.png"
                        },
                        {
                            title:"腾讯文档",
                            desc:"多人协办在线文档",
                            url:"https://docs.qq.com/",
                            image:"docsqq.png"
                        },
                        {
                            title:"Cmd Markdown",
                            desc:"在线Markdown写作",
                            url:"https://www.zybuluo.com/mdeditor",
                            image:"mdeditor.png"
                        },
                    ]
                },
                //在线设计
                {
                    title:"在线设计",
                    nav:[
                        {
                            title:"创客贴",
                            desc:"在线制图1",
                            url:"https://www.chuangkit.com/designtools/startdesign",
                        },
                        {
                            title:"稿定设计",
                            desc:"在线制图2",
                            url:"https://www.gaoding.com/",
                        },
                        {
                            title:"Wordart",
                            desc:"制作文字图案(不fq会很卡)",
                            url:"https://wordart.com/",
                            image:"wordart.png"
                        },
                        {
                            title:"Cool Background",
                            desc:"在线生成背景图或代码",
                            url:"https://coolbackgrounds.io/",
                            image:"coolbackground.png"
                        },
                        {
                            title:"Shapefactory",
                            desc:"在线设计LOGO、渐变图等",
                            url:"https://shapefactory.co/",
                        },
                        {
                            title:"Uigradients",
                            desc:"在线生成渐变色1",
                            url:"https://uigradients.com/",
                        },
                        {
                            title:"Webgradients",
                            desc:"在线生成渐变色2",
                            url:"https://webgradients.com/",
                        },
                        {
                            title:"Colorhunt",
                            desc:"在线配色1",
                            url:"https://colorhunt.co/",
                            image:"colorhunt.png"
                        },
                        {
                            title:"Colordrop",
                            desc:"在线配色2",
                            url:"https://colordrop.io/",
                            image:"colordrop.png"
                        },
                        {
                            title:"Photomosh",
                            desc:"在线生成故障艺术图",
                            url:"https://photomosh.com/",
                            image:"photomosh.png"
                        },
                        {
                            title:"Pixelmap",
                            desc:"在线可视化地图图表生成",
                            url:"https://pixelmap.amcharts.com/",
                            image:"pixelmap.png"
                        },
                        {
                            title:"FLAT SURFACE SHADER",
                            desc:"在线制作lowpoly背景",
                            url:"http://matthew.wagerfield.com/flat-surface-shader/",
                            image:"matthew.png"
                        },
                        {
                            title:"Blobmaker",
                            desc:"在线生成异形图",
                            url:"https://www.blobmaker.app/",
                            image:"blobmaker.png"
                        },
                        {
                            title:"Getwaves",
                            desc:"在线生成波形背景图",
                            url:"https://getwaves.io/",
                            image:"getwaves.png"
                        },
                        {
                            title:"Wangyasai",
                            desc:"放射性图片生成",
                            url:"https://wangyasai.github.io/Stars-Emmision/",
                            image:"wangyasai.png"
                        },
                        {
                            title:"Gif之家",
                            desc:"在线生成gif动态表情包",
                            url:"https://www.gifhome.com/",
                            image:"gifhome.png"
                        },
                        {
                            title:"我爱斗图",
                            desc:"表情包搜索|表情包制作",
                            url:"https://www.52doutu.cn/",
                            image:"52doutu.png"
                        },
                        {
                            title:"BrowserFrame",
                            desc:"在线截图网站全页面(多浏览器可选)",
                            url:"https://browserframe.com/",
                            image:"browserframe.png"
                        },
                        {
                            title:"Screenguru",
                            desc:"在线截图网站全页面(比上一个好看)",
                            url:"https://screen.guru/",
                            image:"screenguru.png"
                        },
                        {
                            title:"Svgbackgrounds",
                            desc:"在线生成SVG背景图",
                            url:"https://www.svgbackgrounds.com/",
                            image:"svgbackgrounds.png"
                        },
                        {
                            title:"Logoly",
                            desc:"在线制作pornhub风格LOGO",
                            url:"https://logoly.pro/",
                            image:"logoly.png"
                        },
                        {
                            title:"Loading.io",
                            desc:"在线设计loading动图",
                            url:"https://loading.io/",
                            image:"loading.png"
                        },
                        {
                            title:"remove.bg",
                            desc:"在线一键抠图",
                            url:"https://www.remove.bg/zh",
                            image:"removebg.png"
                        },
                    ]
                },
                //文件处理
                {
                    title:"文件处理",
                    nav: [
                        {
                            title:"TinyPng",
                            desc:"在线压缩png,jpg图片",
                            url:"https://tinypng.com/",
                            image:"tinypng.png"
                        }, 
                        {
                            title:"Squoosh",
                            desc:"谷歌大佬出品的在线图片压缩",
                            url:"https://squoosh.app/",
                            image:"squoosh.png"
                        }, 
                        {
                            title:"Convertio",
                            desc:"万能的文件格式转化",
                            url:"https://convertio.co/zh/",
                            image:"convertio.png"
                        },
                        {
                            title:"PDF.IO",
                            desc:"PDF在线转化",
                            url:"https://pdf.io/",
                            image:"pdfio.png"
                        },
                        {
                            title:"Smallpdf",
                            desc:"多功能PDF转化器",
                            url:"https://smallpdf.com/",
                            image:"smallpdf.png"
                        },
                        {
                            title:"Iloveimg",
                            desc:"在线批量编辑图片",
                            url:"https://www.iloveimg.com/zh-cn",
                            image:"iloveimg.png"
                        },
                        {
                            title:"蜜蜂剪辑",
                            desc:"在线视频剪辑|视频转GIF",
                            url:"https://beecut.cn/",
                            image:"beecut.png"
                        },
                    ]
                },
                //临时网盘
                {
                    title: "临时网盘",
                    nav:[
                        {
                            title:"牛奶快传",
                            desc:"即用即走的在线大文件传输服务",
                            url:"https://cowtransfer.com/",
                            image:"cowtransfer.png"
                        }, 
                        {
                            title:"文叔叔",
                            desc:"不限速分享大文件在线网盘",
                            url:"https://www.wenshushu.cn/",
                            image:"wenshushu.png"
                        }, 
                        {
                            title:"蓝奏云",
                            desc:"小文件分享不限速网盘",
                            url:"https://www.lanzou.com/",
                            image:"lanzou.png"
                        }, 
                    ]
                },
                //下载工具
                {
                    title:"下载工具",
                    nav: [
                        {
                            title:"唧唧",
                            desc:"下载b站视频|bilibili",
                            url:"https://www.jijidown.com/",
                        },
                        {
                            title:"海盗湾",
                            desc:"BT搜索资源站",
                            url:"http://thepiratebay.se.net/",
                        },
                        {
                            title:"超高无损音乐",
                            desc:"无损音乐免费下载",
                            url:"https://www.sq688.com/",
                            image: "sq688.png"
                        },
                        {
                            title:"QQ音乐解析",
                            desc:"无损音乐解析",
                            url:"http://www.douqq.com/qqmusic/",
                            image: "qqmusic.png"
                        },
                    ]
                },
                //其他工具
                {
                    title: "其他工具",
                    nav: [
                        {
                            title:"懒猴文字识别网页版",
                            desc:"在线ORC(修改localStorage可无限次识别)",
                            url:"https://h5cssjs.com/ocr",
                            image:"h5cssjs.png"
                        },
                        {
                            title:"云短信",
                            desc:"在线免费短信接收|验证码短信",
                            url:"https://www.materialtools.com/",
                        },
                        {
                            title:"隐私短信",
                            desc:"免费在线短信验证码接收码平台",
                            url:"https://www.yinsiduanxin.com/",
                            image:"yinsiduanxin.png"
                        },
                        {
                            title:"Nicetool",
                            desc:"在线小工具大全",
                            url:"http://www.nicetool.net/",
                            image:"nicetool.png"
                        },
                        {
                            title:"工资计算器",
                            desc:"在线计算税后工资",
                            url:"https://hizdm.cn",
                            image:"hizdm.png"
                        },
                    ]
                }
            ]
        },
        
        //购物平台
        {
            title: "购物平台",
            icon: "shopping-cart",
            nav:[
                {
                    title:"什么值得买",
                    desc:"张大妈你值得拥有",
                    url:"https://www.smzdm.com/",
                    image:"smzdm.png"
                },
                {
                    title:"逛丢",
                    desc:"实时同步全网折扣",
                    url:"https://guangdiu.com/",
                    image:"guangdiu.png"
                },
                {
                    title:"京东商城",
                    desc:"支持东哥",
                    url:"https://jd.com",
                    image:"jd.png"
                },
                {
                    title:"淘宝",
                    desc:"不解释",
                    url:"https://taobao.com",
                    image:"taobao.png"
                },
                {
                    title:"京东联盟",
                    desc:"京东返利网站",
                    url:"https://union.jd.com/",
                    image:"jd.png"
                },
                {
                    title:"阿里妈妈",
                    desc:"淘宝返利网站",
                    url:"https://www.alimama.com/",
                    image:"alimama.png"
                },
 {
                    title:"C 盘爆红了",
                    desc:"https://www.chongbuluo.com/thread-14084-1-1.html",
                    url:"https://www.chongbuluo.com/thread-14084-1-1.html",
                    image:"https://favicon.im/www.chongbuluo.com/thread-14084-1-1.html"
                },
                                {
                    title:"Chat For Free",
                    desc:"https://chat.4.bnu120.space/",
                    url:"https://chat.4.bnu120.space/",
                    image:"https://favicon.im/hey.com"
                },
                                {
                    title:"阿金世界 - 聚合导航",
                    desc:"https://ajinworld.top/",
                    url:"https://ajinworld.top/",
                    image:"https://favicon.im/hey.com"
                },
                                {
                    title:"⭐【3000t.top资源文档】⭐",
                    desc:"https://docs.qq.com/sheet/DR3dFWGtDR0xVdVFt?tab=BB08J2",
                    url:"https://docs.qq.com/sheet/DR3dFWGtDR0xVdVFt?tab=BB08J2",
                    image:"https://favicon.im/docs.qq.com/sheet/DR3dFWGtDR0xVdVFt?tab=BB08J2"
                },
                                {
                    title:"46云-香港数据中心服务商,专注香港服务器,高防服务器_46云",
                    desc:"https://www.46yun.com/",
                    url:"https://www.46yun.com/",
                    image:"https://favicon.im/46yun.com"
                },
                                {
                    title:"46",
                    desc:"http://154.9.29.94/",
                    url:"http://154.9.29.94/",
                    image:"https://favicon.im/154.9.29.94"
                },
                                {
                    title:"Rainy Mood |  听见雨的声音",
                    desc:"https://www.rainymood.com/",
                    url:"https://www.rainymood.com/",
                    image:"https://favicon.im/rainymood.com"
                },
                                {
                    title:"tree.fm  |  听见森林的声音",
                    desc:"https://www.tree.fm/forest/18",
                    url:"https://www.tree.fm/forest/18",
                    image:"https://favicon.im/www.tree.fm"
                },
                {
                    title:"GitMind · 思乎 - AI思维导图流程图白板制作软件",
                    desc:"https://gitmind.cn/",
                    url:"https://gitmind.cn/",
                    image:"https://favicon.im/gitmind.cn"
                },
                                {
                    title:"草料二维码 - 微信运营工具导航-公众号运营工具导航-自媒体运营工具导航_自媒体人运营工具导航",
                    desc:"https://123.wxeditor.com/tool-1-44.html",
                    url:"https://123.wxeditor.com/tool-1-44.html",
                    image:"https://favicon.im/123.wxeditor.com/tool-1-44.html"
                },
                                {
                    title:"搜狗微信搜索_订阅号及文章内容独家收录，一搜即达",
                    desc:"https://weixin.sogou.com/",
                    url:"https://weixin.sogou.com/",
                    image:"https://favicon.im/weixin.sogou.com"
                },
                                {
                    title:"考拉新媒体导航——新媒体人的专属门户网站",
                    desc:"https://www.kaolamedia.com/",
                    url:"https://www.kaolamedia.com/",
                    image:"https://favicon.im/www.kaolamedia.com"
                },
                                {
                    title:"优秀新媒体导航-媒帮派",
                    desc:"http://123.meibp.com/",
                    url:"http://123.meibp.com/",
                    image:"https://favicon.im/123.meibp.com"
                },
                                {
                    title:"微信公众号 Markdown 排版编辑器 | Quail 工具",
                    desc:"https://quail.ink/tools/markdown-to-wx/",
                    url:"https://quail.ink/tools/markdown-to-wx/",
                    image:"https://favicon.im/quail.ink/tools/markdown-to-wx"
                },
                                {
                    title:"135编辑器官网_微信公众号图文排版工具_一键在线文章内容编辑器",
                    desc:"https://www.135editor.com/",
                    url:"https://www.135editor.com/",
                    image:"https://favicon.im/www.135editor.com"
                },
                                {
                    title:"秀米_公众号图文编辑器和H5制作 - 秀米XIUMI",
                    desc:"https://xiumi.us/#/",
                    url:"https://xiumi.us/#/",
                    image:"https://favicon.im/xiumi.us/#"
                },
                                {
                    title:"微信编辑器_微信排版_微信图文编辑器_公众号编辑_微信排版工具_i排版官网",
                    desc:"https://ipaiban.com/",
                    url:"https://ipaiban.com/",
                    image:"https://favicon.im/ipaiban.com"
                },
                                {
                    title:"96微信编辑器官网--微信公众平台图文排版工具 微信编辑器哪个好 在线内容编辑软件",
                    desc:"https://bj.96weixin.com/",
                    url:"https://bj.96weixin.com/",
                    image:"https://favicon.im/bj.96weixin.com"
                },
                                {
                    title:"壹伴官网_微信编辑器_公众号助手_公众号排版_一键图文排版",
                    desc:"https://yiban.io/",
                    url:"https://yiban.io/",
                    image:"https://favicon.im/yiban.io"
                },
                                {
                    title:"美编_简单好用的公众号运营助手、微信编辑器和多账号管理公众号助手",
                    desc:"https://www.mbian.com/",
                    url:"https://www.mbian.com/",
                    image:"https://favicon.im/www.mbian.com"
                },
                                {
                    title:"微小宝公众号文章编辑器—公众号图文排版神器",
                    desc:"https://editor.wxb.com/",
                    url:"https://editor.wxb.com/",
                    image:"https://favicon.im/editor.wxb.com"
                },
                                {
                    title:"易点微信编辑器_微信公众号排版_公众号软文编辑_公众号图文编辑_微信图文排版工具_微信内容排版软件_微信公众平台素材编辑-易点编辑器",
                    desc:"https://www.wxeditor.com/",
                    url:"https://www.wxeditor.com/",
                    image:"https://favicon.im/www.wxeditor.com"
                },
                                {
                    title:"AI工具集 | 700+ AI工具集合官网，国内外AI工具集导航大全",
                    desc:"https://ai-bot.cn/",
                    url:"https://ai-bot.cn/",
                    image:"https://favicon.im/ai-bot.cn"
                },
                                {
                    title:"爱润色-人工智能润色改写工具",
                    desc:"https://aiwyc.com/#/",
                    url:"https://aiwyc.com/#/",
                    image:"https://favicon.im/aiwyc.com/#"
                },
                                {
                    title:"人工智能AI伪原创 - 媒帮派伪原创",
                    desc:"https://ai.meibp.com/",
                    url:"https://ai.meibp.com/",
                    image:"https://favicon.im/ai.meibp.com"
                },
                                {
                    title:"B站",
                    desc:"https://passport.bilibili.com/login",
                    url:"https://passport.bilibili.com/login",
                    image:"https://favicon.im/passport.bilibili.com/login"
                },
                                {
                    title:"微博",
                    desc:"https://weibo.com/newlogin?tabtype=weibo&gid=102803&openLoginLayer=0&url=https%3A%2F%2Fweibo.com%2F",
                    url:"https://weibo.com/newlogin?tabtype=weibo&gid=102803&openLoginLayer=0&url=https%3A%2F%2Fweibo.com%2F",
                    image:"https://favicon.im/weibo.com/newlogin?tabtype=weibo&gid=102803&openLoginLayer=0&url=https%3A%2F%2Fweibo.com%2F"
                },
                                {
                    title:"知乎",
                    desc:"https://www.zhihu.com/signin?next=%2F",
                    url:"https://www.zhihu.com/signin?next=%2F",
                    image:"https://favicon.im/www.zhihu.com/signin?next=%2F"
                },
                                {
                    title:"微博",
                    desc:"https://open.weibo.com/development/datacenter",
                    url:"https://open.weibo.com/development/datacenter",
                    image:"https://favicon.im/open.weibo.com/development/datacenter"
                },
                                {
                    title:"百家号",
                    desc:"https://baijiahao.baidu.com/builder/theme/bjh/login",
                    url:"https://baijiahao.baidu.com/builder/theme/bjh/login",
                    image:"https://favicon.im/baijiahao.baidu.com/builder/theme/bjh/login"
                },
                                {
                    title:"视频号助手",
                    desc:"https://channels.weixin.qq.com/login.html",
                    url:"https://channels.weixin.qq.com/login.html",
                    image:"https://favicon.im/channels.weixin.qq.com/login.html"
                },
                                {
                    title:"抖音后台",
                    desc:"https://creator.douyin.com/",
                    url:"https://creator.douyin.com/",
                    image:"https://favicon.im/creator.douyin.com"
                },
                                {
                    title:"企鹅号",
                    desc:"https://om.qq.com/userAuth/index",
                    url:"https://om.qq.com/userAuth/index",
                    image:"https://favicon.im/om.qq.com/userAuth/index"
                },
                                {
                    title:"头条号",
                    desc:"https://mp.toutiao.com/auth/page/login?redirect_url=JTJGcHJvZmlsZV92NCUyRg==",
                    url:"https://mp.toutiao.com/auth/page/login?redirect_url=JTJGcHJvZmlsZV92NCUyRg==",
                    image:"https://favicon.im/mp.toutiao.com/auth/page/login?redirect_url=JTJGcHJvZmlsZV92NCUyRg=="
                },
                                {
                    title:"小红书创作服务平台",
                    desc:"https://creator.xiaohongshu.com/login?source=official",
                    url:"https://creator.xiaohongshu.com/login?source=official",
                    image:"https://favicon.im/creator.xiaohongshu.com/login?source=official"
                },
                                {
                    title:"网易号",
                    desc:"https://mp.163.com/wemedia/login.html#/",
                    url:"https://mp.163.com/wemedia/login.html#/",
                    image:"https://favicon.im/mp.163.com/wemedia/login.html#"
                },
                                {
                    title:"百度贴吧",
                    desc:"https://tieba.baidu.com/index.html",
                    url:"https://tieba.baidu.com/index.html",
                    image:"https://favicon.im/tieba.baidu.com/index.html"
                },
                                {
                    title:"简书",
                    desc:"https://www.jianshu.com/",
                    url:"https://www.jianshu.com/",
                    image:"https://favicon.im/www.jianshu.com"
                },
                                {
                    title:"豆瓣",
                    desc:"https://www.douban.com/",
                    url:"https://www.douban.com/",
                    image:"https://favicon.im/www.douban.com"
                },
                                {
                    title:"大鱼号官网",
                    desc:"https://mp.dayu.com/",
                    url:"https://mp.dayu.com/",
                    image:"https://favicon.im/mp.dayu.com"
                },
                                {
                    title:"注意！！！资源具有时效性，商用请注意看说明，侵权概不负责",
                    desc:"edge://newtab/",
                    url:"edge://newtab/",
                    image:"https://favicon.im/edge://newtab"
                },
                                {
                    title:"应用软件｜那些免费的砖，发现免费可商用的资源",
                    desc:"https://www.thosefree.com/apps",
                    url:"https://www.thosefree.com/apps",
                    image:"https://favicon.im/www.thosefree.com/apps"
                },
                                {
                    title:"PICKFREE - 免费资源导航|免版权图片|免费商用字体|免费音频、视频等设计素材下载",
                    desc:"http://www.pickfree.cn/",
                    url:"http://www.pickfree.cn/",
                    image:"https://favicon.im/www.pickfree.cn"
                },
                                {
                    title:"免费素材图片 · Pexels",
                    desc:"https://www.pexels.com/zh-cn/",
                    url:"https://www.pexels.com/zh-cn/",
                    image:"https://favicon.im/www.pexels.com/zh-cn"
                },
                                {
                    title:"1 million+ Stunning Free Images to Use Anywhere - Pixabay",
                    desc:"https://pixabay.com/",
                    url:"https://pixabay.com/",
                    image:"https://favicon.im/pixabay.com"
                },
                                {
                    title:"Blush  |  大家都可以用的插图工具",
                    desc:"https://blush.design/zh-CN?utm_source=appinn.com",
                    url:"https://blush.design/zh-CN?utm_source=appinn.com",
                    image:"https://favicon.im/blush.design/zh-CN?utm_source=appinn.com"
                },
                                {
                    title:"Beautiful Free Images & Pictures | Unsplash",
                    desc:"https://unsplash.com/",
                    url:"https://unsplash.com/",
                    image:"https://favicon.im/unsplash.com"
                },
                                {
                    title:"用于商业用途的免版税矢量插图 |规模",
                    desc:"https://scale.flexiple.com/illustrations/",
                    url:"https://scale.flexiple.com/illustrations/",
                    image:"https://favicon.im/scale.flexiple.com/illustrations"
                },
                                {
                    title:"由一流设计师设计的免费图标 |图标存储",
                    desc:"https://iconstore.co/",
                    url:"https://iconstore.co/",
                    image:"https://favicon.im/iconstore.co"
                },
                                {
                    title:"猫啃网  |  无版权可商用免费中文字体下载大全图文版",
                    desc:"https://www.maoken.com/all-fonts-imgs",
                    url:"https://www.maoken.com/all-fonts-imgs",
                    image:"https://favicon.im/www.maoken.com/all-fonts-imgs"
                },
                                {
                    title:"100font.com |  免费字体下载 - 免费商用字体下载网站",
                    desc:"https://www.100font.com/",
                    url:"https://www.100font.com/",
                    image:"https://favicon.im/www.100font.com"
                },
                                {
                    title:"小森平的免费下载音效",
                    desc:"https://taira-komori.jpn.org/freesoundcn.html",
                    url:"https://taira-komori.jpn.org/freesoundcn.html",
                    image:"https://favicon.im/taira-komori.jpn.org/freesoundcn.html"
                },
                                {
                    title:"淘声网 | toSound声音搜索引擎 - 免费音效素材资源|视频游戏配乐下载",
                    desc:"https://www.tosound.com/",
                    url:"https://www.tosound.com/",
                    image:"https://favicon.im/www.tosound.com"
                },
                                {
                    title:"免费库存视频、下载免版税视频|Depositphotos ® 混合套件",
                    desc:"https://mixkit.co/free-stock-video/",
                    url:"https://mixkit.co/free-stock-video/",
                    image:"https://favicon.im/mixkit.co/free-stock-video"
                },
                                {
                    title:"稿定设计-做图做视频必备_在线设计神器_海量版权素材模板",
                    desc:"https://www.gaoding.com/",
                    url:"https://www.gaoding.com/",
                    image:"https://favicon.im/www.gaoding.com"
                },
                                {
                    title:"创客贴_平面设计作图神器_免费设计模板_在线搞定设计印刷",
                    desc:"https://www.chuangkit.com/",
                    url:"https://www.chuangkit.com/",
                    image:"https://favicon.im/www.chuangkit.com"
                },
                                {
                    title:"蚁小二官网 - 帮您管理所有的新媒体账号",
                    desc:"https://www.yixiaoer.cn/",
                    url:"https://www.yixiaoer.cn/",
                    image:"https://favicon.im/www.yixiaoer.cn"
                },
                                {
                    title:"易媒助手官网 | 短视频一键分发同布 自媒体多账号管理",
                    desc:"https://yimeizhushou.com/",
                    url:"https://yimeizhushou.com/",
                    image:"https://favicon.im/yimeizhushou.com"
                },
                                {
                    title:"微信公众平台",
                    desc:"https://mp.weixin.qq.com/",
                    url:"https://mp.weixin.qq.com/",
                    image:"https://favicon.im/mp.weixin.qq.com"
                },
                                {
                    title:"markdown | 文章排版",
                    desc:"https://editor.mdnice.com/",
                    url:"https://editor.mdnice.com/",
                    image:"https://favicon.im/editor.mdnice.com"
                },
                                {
                    title:"简单设计 | 封面设计",
                    desc:"https://jiandan.link/app/home",
                    url:"https://jiandan.link/app/home",
                    image:"https://favicon.im/jiandan.link/app/home"
                },
                                {
                    title:"易撰 | 原创检测+爆文库",
                    desc:"https://zmt.yizhuan5.com/work.html#1-4",
                    url:"https://zmt.yizhuan5.com/work.html#1-4",
                    image:"https://favicon.im/zmt.yizhuan5.com/work.html#1-4"
                },
                                {
                    title:"新榜 | 接广平台",
                    desc:"https://newrank.cn/user/login?displayType=login&backUrl=https%3A%2F%2Fedit.newrank.cn%2F",
                    url:"https://newrank.cn/user/login?displayType=login&backUrl=https%3A%2F%2Fedit.newrank.cn%2F",
                    image:"https://favicon.im/newrank.cn/user/login?displayType=login&backUrl=https%3A%2F%2Fedit.newrank.cn%2F"
                },
                                {
                    title:"微信公众平台",
                    desc:"https://mp.weixin.qq.com/",
                    url:"https://mp.weixin.qq.com/",
                    image:"https://favicon.im/mp.weixin.qq.com"
                },
                                {
                    title:"markdown | 文章排版",
                    desc:"https://editor.mdnice.com/",
                    url:"https://editor.mdnice.com/",
                    image:"https://favicon.im/editor.mdnice.com"
                },
                                {
                    title:"135编辑器 | 编辑器",
                    desc:"https://www.135editor.com/",
                    url:"https://www.135editor.com/",
                    image:"https://favicon.im/www.135editor.com"
                },
                                {
                    title:"易撰 | 原创检测",
                    desc:"https://zmt.yizhuan5.com/work.html#1-4",
                    url:"https://zmt.yizhuan5.com/work.html#1-4",
                    image:"https://favicon.im/zmt.yizhuan5.com/work.html#1-4"
                },
                                {
                    title:"新榜 | 接广平台",
                    desc:"https://newrank.cn/user/login?displayType=login&backUrl=https%3A%2F%2Fedit.newrank.cn%2F",
                    url:"https://newrank.cn/user/login?displayType=login&backUrl=https%3A%2F%2Fedit.newrank.cn%2F",
                    image:"https://favicon.im/newrank.cn/user/login?displayType=login&backUrl=https%3A%2F%2Fedit.newrank.cn%2F"
                },
                                {
                    title:"Kimi | AI辅助写作",
                    desc:"https://kimi.moonshot.cn/",
                    url:"https://kimi.moonshot.cn/",
                    image:"https://favicon.im/kimi.moonshot.cn"
                },
                                {
                    title:"微信公众号同步助手 - 公众号文章多平台同步 Typora Markdown写作 一文多发 自媒体内容同步、内容营销、分发工具，自媒体助手，一键同步发布，支持微博头条、掘金、CSDN、今日头条、豆瓣、WordPress博客、知乎专栏、简书、Typecho博客等各大内容平台",
                    desc:"https://www.wechatsync.com/",
                    url:"https://www.wechatsync.com/",
                    image:"https://favicon.im/www.wechatsync.com"
                },
                                {
                    title:"AI助手中心",
                    desc:"https://inspiration.baidu.com/app?refer_page=&srcid=&tplname=&order=&lid=&source=input&is_immersed=0&stk=&isNewPage=0",
                    url:"https://inspiration.baidu.com/app?refer_page=&srcid=&tplname=&order=&lid=&source=input&is_immersed=0&stk=&isNewPage=0",
                    image:"https://favicon.im/inspiration.baidu.com/app?refer_page=&srcid=&tplname=&order=&lid=&source=input&is_immersed=0&stk=&isNewPage=0"
                },
                                {
                    title:"AiShort(ChatGPT Shortcut)-简单易用的 AI 快捷指令表，让生产力倍增！ | AiShort(ChatGPT Shortcut)-AI Prompt Management,Productivity Tool",
                    desc:"https://www.aishort.top/",
                    url:"https://www.aishort.top/",
                    image:"https://favicon.im/www.aishort.top"
                },
                                {
                    title:"简体中文 人工智能内容检测器 - Smodin",
                    desc:"https://smodin.io/zh-cn/ai%E5%86%85%E5%AE%B9%E6%A3%80%E6%B5%8B%E5%99%A8",
                    url:"https://smodin.io/zh-cn/ai%E5%86%85%E5%AE%B9%E6%A3%80%E6%B5%8B%E5%99%A8",
                    image:"https://favicon.im/smodin.io/zh-cn/ai%E5%86%85%E5%AE%B9%E6%A3%80%E6%B5%8B%E5%99%A8"
                },
                                {
                    title:"在线文档相似度计算、在线计算文章相似度、计算网页相似度！--查错网",
                    desc:"http://life.chacuo.net/convertsimilar",
                    url:"http://life.chacuo.net/convertsimilar",
                    image:"https://favicon.im/life.chacuo.net/convertsimilar"
                },
                                {
                    title:"BingAI聊天 - 小天智能助手",
                    desc:"https://bing.jk.cm/web/index.html?showconv=1#/",
                    url:"https://bing.jk.cm/web/index.html?showconv=1#/",
                    image:"https://favicon.im/bing.jk.cm/web/index.html?showconv=1#"
                },
                                {
                    title:"夸克网盘资源-优秀的夸克资源分享社",
                    desc:"https://www.ppat.top/?utm_source=AI%E7%A5%9E%E5%99%A8%E9%9B%86",
                    url:"https://www.ppat.top/?utm_source=AI%E7%A5%9E%E5%99%A8%E9%9B%86",
                    image:"https://favicon.im/www.ppat.top/?utm_source=AI%E7%A5%9E%E5%99%A8%E9%9B%86"
                },
                                {
                    title:"V2方圆 – 发掘稀缺资源 v2fy zhaoolee",
                    desc:"https://v2fy.com/",
                    url:"https://v2fy.com/",
                    image:"https://favicon.im/v2fy.com"
                },
                                {
                    title:"UndetectableGPT.ai：用免费在线不可检测AI人性化工具绕过GPTZero",
                    desc:"https://undetectablegpt.ai/zh-CN",
                    url:"https://undetectablegpt.ai/zh-CN",
                    image:"https://favicon.im/undetectablegpt.ai/zh-CN"
                },
                                {
                    title:"Humanize.im：在线免费人性化AI文本",
                    desc:"https://humanize.im/zh-CN",
                    url:"https://humanize.im/zh-CN",
                    image:"https://favicon.im/humanize.im/zh-CN"
                },
                                {
                    title:"Turnitin免费平替：AI抄袭检测器 | ZeroGPT Plus",
                    desc:"https://www.zerogpt.plus/cn?utm_source=AI%E7%A5%9E%E5%99%A8%E9%9B%86",
                    url:"https://www.zerogpt.plus/cn?utm_source=AI%E7%A5%9E%E5%99%A8%E9%9B%86",
                    image:"https://favicon.im/www.zerogpt.plus/cn?utm_source=AI%E7%A5%9E%E5%99%A8%E9%9B%86"
                },
                                {
                    title:"爱润色-人工智能润色改写工具",
                    desc:"https://aiwyc.com/#/",
                    url:"https://aiwyc.com/#/",
                    image:"https://favicon.im/aiwyc.com/#"
                },
                                {
                    title:"ChatGPT 指令大全｜ExplainThis",
                    desc:"https://www.explainthis.io/zh-hant/chatgpt",
                    url:"https://www.explainthis.io/zh-hant/chatgpt",
                    image:"https://favicon.im/www.explainthis.io/zh-hant/chatgpt"
                },
                                {
                    title:"‍‌​​﻿⁤⁤​﻿﻿⁣​​‍⁤﻿‌​‌​⁡‬​‍⁤‍​﻿​﻿‍﻿⁣​‬​⁣⁤‬​​⁢‬‬⁢﻿⁡‌‌‌超级大礼：《国外价值2万的超级提示词》 - 飞书云文档",
                    desc:"https://fizaghzgugc.feishu.cn/wiki/B5wCw3qxui2HaykpyKBcKxxEnTg",
                    url:"https://fizaghzgugc.feishu.cn/wiki/B5wCw3qxui2HaykpyKBcKxxEnTg",
                    image:"https://favicon.im/fizaghzgugc.feishu.cn/wiki/B5wCw3qxui2HaykpyKBcKxxEnTg"
                },
                                {
                    title:"极致了 - 微信公众号API接口文章素材小程序实时数据查询采集分析工具",
                    desc:"https://www.dajiala.com/",
                    url:"https://www.dajiala.com/",
                    image:"https://favicon.im/www.dajiala.com"
                },
                                {
                    title:"次幂数据 - 公众号数据分析平台",
                    desc:"https://www.cimidata.com/",
                    url:"https://www.cimidata.com/",
                    image:"https://favicon.im/www.cimidata.com"
                },
                                {
                    title:"西瓜自媒体数据",
                    desc:"https://data.xiguaji.com/",
                    url:"https://data.xiguaji.com/",
                    image:"https://favicon.im/data.xiguaji.com"
                },
                                {
                    title:"135编辑器",
                    desc:"https://www.135editor.com/",
                    url:"https://www.135editor.com/",
                    image:"https://favicon.im/www.135editor.com"
                },
                                {
                    title:"壹伴微信编辑器",
                    desc:"https://yiban.io/",
                    url:"https://yiban.io/",
                    image:"https://favicon.im/yiban.io"
                },
                                {
                    title:"秀米 XIUMI",
                    desc:"https://xiumi.us/#/",
                    url:"https://xiumi.us/#/",
                    image:"https://favicon.im/xiumi.us/#"
                },
                                {
                    title:"微小宝-微信私域流量运营专家，百万用户的选择 - 微小宝助手_微小宝",
                    desc:"https://www.wxb.com/",
                    url:"https://www.wxb.com/",
                    image:"https://favicon.im/www.wxb.com"
                },
                                {
                    title:"微信编辑器 微信公众平台图文排版工具 微信编辑器素材--主编微信编辑器",
                    desc:"https://www.zhubian.com/",
                    url:"https://www.zhubian.com/",
                    image:"https://favicon.im/www.zhubian.com"
                },
                                {
                    title:"MDX Editor | 一个微信排版编辑器，使用 MDX 来排版",
                    desc:"https://editor.runjs.cool/post?id=demo",
                    url:"https://editor.runjs.cool/post?id=demo",
                    image:"https://favicon.im/editor.runjs.cool/post?id=demo"
                },
                                {
                    title:"今日热榜官网  |  看各大平台热搜",
                    desc:"https://tophub.today/",
                    url:"https://tophub.today/",
                    image:"https://favicon.im/tophub.today"
                },
                                {
                    title:"新榜微信编辑器—让你的图文编辑生动有趣",
                    desc:"https://edit.newrank.cn/",
                    url:"https://edit.newrank.cn/",
                    image:"https://favicon.im/edit.newrank.cn"
                },
                                {
                    title:"易撰自媒体工具_让内容创作更高效",
                    desc:"https://www.yizhuan5.com/work.html#1-4",
                    url:"https://www.yizhuan5.com/work.html#1-4",
                    image:"https://favicon.im/www.yizhuan5.com/work.html#1-4"
                },
                                {
                    title:"PICKFREE - 免费资源导航|免版权图片|免费商用字体|免费音频、视频等设计素材下载",
                    desc:"http://www.pickfree.cn/",
                    url:"http://www.pickfree.cn/",
                    image:"https://favicon.im/www.pickfree.cn"
                },
                                {
                    title:"免费素材图片 · Pexels",
                    desc:"https://www.pexels.com/zh-cn/",
                    url:"https://www.pexels.com/zh-cn/",
                    image:"https://favicon.im/www.pexels.com/zh-cn"
                },
                                {
                    title:"1 million+ Stunning Free Images to Use Anywhere - Pixabay",
                    desc:"https://pixabay.com/",
                    url:"https://pixabay.com/",
                    image:"https://favicon.im/pixabay.com"
                },
                                {
                    title:"Blush  |  大家都可以用的插图工具",
                    desc:"https://blush.design/zh-CN?utm_source=appinn.com",
                    url:"https://blush.design/zh-CN?utm_source=appinn.com",
                    image:"https://favicon.im/blush.design/zh-CN?utm_source=appinn.com"
                },
                                {
                    title:"Beautiful Free Images & Pictures | Unsplash",
                    desc:"https://unsplash.com/",
                    url:"https://unsplash.com/",
                    image:"https://favicon.im/unsplash.com"
                },
                                {
                    title:"Royalty free Vector Illustrations for Commercial Use | Scale",
                    desc:"https://scale.flexiple.com/illustrations/",
                    url:"https://scale.flexiple.com/illustrations/",
                    image:"https://favicon.im/scale.flexiple.com/illustrations"
                },
                                {
                    title:"简单设计EasyDesign-免费在线设计工具图片处理工具",
                    desc:"https://jiandan.link/app/home",
                    url:"https://jiandan.link/app/home",
                    image:"https://favicon.im/jiandan.link/app/home"
                },
                                {
                    title:"创客贴_平面设计作图神器_免费设计模板_在线搞定设计印刷",
                    desc:"https://www.chuangkit.com/designtools/designindex",
                    url:"https://www.chuangkit.com/designtools/designindex",
                    image:"https://favicon.im/www.chuangkit.com/designtools/designindex"
                },
                                {
                    title:"稿定设计-做图做视频必备_在线设计神器_海量版权素材模板",
                    desc:"https://www.gaoding.com/",
                    url:"https://www.gaoding.com/",
                    image:"https://favicon.im/www.gaoding.com"
                },
                                {
                    title:"Canva在线平面设计",
                    desc:"https://www.canva.cn/",
                    url:"https://www.canva.cn/",
                    image:"https://favicon.im/www.canva.cn"
                },
                                {
                    title:"在线设计 | 图怪兽",
                    desc:"https://818ps.com/",
                    url:"https://818ps.com/",
                    image:"https://favicon.im/818ps.com"
                },
                                {
                    title:"黄油相机 | iOS/Android",
                    desc:"https://www.bybutter.com/",
                    url:"https://www.bybutter.com/",
                    image:"https://favicon.im/www.bybutter.com"
                },
                                {
                    title:"猫啃网  |  无版权可商用免费中文字体下载大全图文版",
                    desc:"https://www.maoken.com/all-fonts-imgs",
                    url:"https://www.maoken.com/all-fonts-imgs",
                    image:"https://favicon.im/www.maoken.com/all-fonts-imgs"
                },
                                {
                    title:"100font.com |  免费字体下载 - 免费商用字体下载网站",
                    desc:"https://www.100font.com/",
                    url:"https://www.100font.com/",
                    image:"https://favicon.im/www.100font.com"
                },
                                {
                    title:"句子控",
                    desc:"https://www.juzikong.com/",
                    url:"https://www.juzikong.com/",
                    image:"https://favicon.im/www.juzikong.com"
                },
                                {
                    title:"营销热点日历",
                    desc:"https://www.adguider.com/calendar?ref=juxuan.pro",
                    url:"https://www.adguider.com/calendar?ref=juxuan.pro",
                    image:"https://favicon.im/www.adguider.com/calendar?ref=juxuan.pro"
                },
                                {
                    title:"抖词词_抖音违禁词检测工具_2024抖音违禁词在线检测_抖音违禁词查询_抖音敏感词检测工具_抖音直播违禁词_广告法违禁词检测",
                    desc:"https://www.doucici.com/",
                    url:"https://www.doucici.com/",
                    image:"https://favicon.im/www.doucici.com"
                },
                                {
                    title:"在线通用违禁词查询工具 - 违禁词查询",
                    desc:"https://www.txttool.com/t/?id=NDY4",
                    url:"https://www.txttool.com/t/?id=NDY4",
                    image:"https://favicon.im/www.txttool.com/t/?id=NDY4"
                },
                                {
                    title:"新广告法禁用词检测 - 站长工具",
                    desc:"https://stool.chinaz.com/vabkeywords/",
                    url:"https://stool.chinaz.com/vabkeywords/",
                    image:"https://favicon.im/stool.chinaz.com/vabkeywords"
                },
                                {
                    title:"广告法违禁词查询",
                    desc:"http://www.ju1.cn/",
                    url:"http://www.ju1.cn/",
                    image:"https://favicon.im/www.ju1.cn"
                },
                                {
                    title:"UndetectableGPT.ai：用免费在线不可检测AI人性化工具绕过GPTZero",
                    desc:"https://undetectablegpt.ai/zh-CN",
                    url:"https://undetectablegpt.ai/zh-CN",
                    image:"https://favicon.im/undetectablegpt.ai/zh-CN"
                },
                                {
                    title:"爱润色-人工智能润色改写工具",
                    desc:"https://aiwyc.com/#/",
                    url:"https://aiwyc.com/#/",
                    image:"https://favicon.im/aiwyc.com/#"
                },
                                {
                    title:"人工智能AI伪原创 - 媒帮派伪原创",
                    desc:"https://ai.meibp.com/",
                    url:"https://ai.meibp.com/",
                    image:"https://favicon.im/ai.meibp.com"
                },
                                {
                    title:"草料二维码",
                    desc:"https://cli.im/",
                    url:"https://cli.im/",
                    image:"https://favicon.im/cli.im"
                },
                                {
                    title:"腾讯问卷",
                    desc:"https://wj.qq.com/",
                    url:"https://wj.qq.com/",
                    image:"https://favicon.im/wj.qq.com"
                },
                                {
                    title:"GitMind · 思乎 - AI思维导图流程图白板制作软件",
                    desc:"https://gitmind.cn/",
                    url:"https://gitmind.cn/",
                    image:"https://favicon.im/gitmind.cn"
                },
                                {
                    title:"搜狗微信搜索_订阅号及文章内容独家收录，一搜即达",
                    desc:"https://weixin.sogou.com/",
                    url:"https://weixin.sogou.com/",
                    image:"https://favicon.im/weixin.sogou.com"
                },
                                {
                    title:"一键获取微信公众号历史消息链接",
                    desc:"https://www.weixinzg.cn/getHomeUrl.html",
                    url:"https://www.weixinzg.cn/getHomeUrl.html",
                    image:"https://favicon.im/www.weixinzg.cn/getHomeUrl.html"
                },
                                {
                    title:"蚁小二官网 - 帮您管理所有的新媒体账号",
                    desc:"https://www.yixiaoer.cn/",
                    url:"https://www.yixiaoer.cn/",
                    image:"https://favicon.im/www.yixiaoer.cn"
                },
                                {
                    title:"易媒助手官网 | 短视频一键分发同布 自媒体多账号管理",
                    desc:"https://yimeizhushou.com/",
                    url:"https://yimeizhushou.com/",
                    image:"https://favicon.im/yimeizhushou.com"
                },
                                {
                    title:"知乎 |  很多程序人喜欢泡在知乎",
                    desc:"https://www.zhihu.com/",
                    url:"https://www.zhihu.com/",
                    image:"https://favicon.im/www.zhihu.com"
                },
                                {
                    title:"今日头条搜索（字节跳动各个app的内部搜索聚合）",
                    desc:"https://www.toutiao.com/",
                    url:"https://www.toutiao.com/",
                    image:"https://favicon.im/www.toutiao.com"
                },
                                {
                    title:"小红书",
                    desc:"https://www.xiaohongshu.com/explore",
                    url:"https://www.xiaohongshu.com/explore",
                    image:"https://favicon.im/www.xiaohongshu.com/explore"
                },
                                {
                    title:"百度贴吧",
                    desc:"https://tieba.baidu.com/",
                    url:"https://tieba.baidu.com/",
                    image:"https://favicon.im/tieba.baidu.com"
                },
                                {
                    title:"微博 – 随时随地发现新鲜事",
                    desc:"https://weibo.com/newlogin?tabtype=weibo&gid=102803&openLoginLayer=0&url=https%3A%2F%2Fweibo.com%2F",
                    url:"https://weibo.com/newlogin?tabtype=weibo&gid=102803&openLoginLayer=0&url=https%3A%2F%2Fweibo.com%2F",
                    image:"https://favicon.im/weibo.com/newlogin?tabtype=weibo&gid=102803&openLoginLayer=0&url=https%3A%2F%2Fweibo.com%2F"
                },
                                {
                    title:"企鹅号（3篇）",
                    desc:"https://om.qq.com/userAuth/index",
                    url:"https://om.qq.com/userAuth/index",
                    image:"https://favicon.im/om.qq.com/userAuth/index"
                },
                                {
                    title:"简书 - 创作你的创作",
                    desc:"https://www.jianshu.com/?ref=juxuan.pro",
                    url:"https://www.jianshu.com/?ref=juxuan.pro",
                    image:"https://favicon.im/www.jianshu.com/?ref=juxuan.pro"
                },
                                {
                    title:"百家号",
                    desc:"https://baijiahao.baidu.com/",
                    url:"https://baijiahao.baidu.com/",
                    image:"https://favicon.im/baijiahao.baidu.com"
                },
                                {
                    title:"Free Font - 收录商用免费字体(汉字英文字体)",
                    desc:"https://font.ittools.cc/",
                    url:"https://font.ittools.cc/",
                    image:"https://favicon.im/font.ittools.cc"
                },
                                {
                    title:"Humanizar Texto IA (Gratis y sin necesidad de registro)",
                    desc:"https://humanizartextoia.ai/?utm_source=AI%E7%A5%9E%E5%99%A8%E9%9B%86",
                    url:"https://humanizartextoia.ai/?utm_source=AI%E7%A5%9E%E5%99%A8%E9%9B%86",
                    image:"https://favicon.im/humanizartextoia.ai/?utm_source=AI%E7%A5%9E%E5%99%A8%E9%9B%86"
                },
                                {
                    title:"LogoAI.ai: 免费在线AI Logo生成器",
                    desc:"https://logoai.ai/zh-CN/app",
                    url:"https://logoai.ai/zh-CN/app",
                    image:"https://favicon.im/logoai.ai/zh-CN/app"
                },
                                {
                    title:"vercel可以部署的项目 - 资源荟萃 - LINUX DO",
                    desc:"https://linux.do/t/topic/80296",
                    url:"https://linux.do/t/topic/80296",
                    image:"https://favicon.im/linux.do/t/topic/80296"
                },
                                {
                    title:"小世界挂载 - 夸克网盘资源 - 爱盘搜",
                    desc:"https://aipanso.com/search?k=%E5%B0%8F%E4%B8%96%E7%95%8C%E6%8C%82%E8%BD%BD",
                    url:"https://aipanso.com/search?k=%E5%B0%8F%E4%B8%96%E7%95%8C%E6%8C%82%E8%BD%BD",
                    image:"https://favicon.im/aipanso.com/search?k=%E5%B0%8F%E4%B8%96%E7%95%8C%E6%8C%82%E8%BD%BD"
                },
                                {
                    title:"Vidful.ai：Kling AI和Luma Dream Machine驱动的免费AI视频生成器",
                    desc:"https://vidful.ai/zh-CN",
                    url:"https://vidful.ai/zh-CN",
                    image:"https://favicon.im/vidful.ai/zh-CN"
                },
                                {
                    title:"首页 - Startab.cn",
                    desc:"https://startab.cn/?utm_source=AI%E7%A5%9E%E5%99%A8%E9%9B%86",
                    url:"https://startab.cn/?utm_source=AI%E7%A5%9E%E5%99%A8%E9%9B%86",
                    image:"https://favicon.im/startab.cn/?utm_source=AI%E7%A5%9E%E5%99%A8%E9%9B%86"
                },
                                {
                    title:"知豆AI - AI对话、RAG智能体、绘画、音乐视频聚合平台",
                    desc:"https://pro.zhidouai.com/dialogue/chat",
                    url:"https://pro.zhidouai.com/dialogue/chat",
                    image:"https://favicon.im/pro.zhidouai.com/dialogue/chat"
                },
                                {
                    title:"⁣⁡​⁤⁣⁤⁣⁣⁢‍﻿⁤⁢⁡⁢‌​​​⁣​⁤‬⁢⁤​‍‬‍‌⁤⁡⁢⁣​⁣‍⁡‬‍‍⁢​⁡‬‬‬⁡小红书问答手册 🔖 - 飞书云文档",
                    desc:"https://xz5ou9rij0.feishu.cn/wiki/wikcnp0sht2c74Pr9wPlqNGSX0g",
                    url:"https://xz5ou9rij0.feishu.cn/wiki/wikcnp0sht2c74Pr9wPlqNGSX0g",
                    image:"https://favicon.im/xz5ou9rij0.feishu.cn/wiki/wikcnp0sht2c74Pr9wPlqNGSX0g"
                },
                                {
                    title:"红抖AI盒子 - 一站式自媒体创作工具平台,短视频图文在线创作工具集合,作品搬运二次创作必备",
                    desc:"https://hd-box.lingandata.com/",
                    url:"https://hd-box.lingandata.com/",
                    image:"https://favicon.im/hd-box.lingandata.com"
                },
                                {
                    title:"引流 - GitMind",
                    desc:"https://gitmind.cn/app/docs/mw75nv5j",
                    url:"https://gitmind.cn/app/docs/mw75nv5j",
                    image:"https://favicon.im/gitmind.cn/app/docs/mw75nv5j"
                },
                                {
                    title:"文皮皮 - 独立的第三方在线抄袭检测工具",
                    desc:"http://www.wenpipi.com/sim",
                    url:"http://www.wenpipi.com/sim",
                    image:"https://favicon.im/www.wenpipi.com/sim"
                },
                                {
                    title:"Chat100.ai：免费使用ChatGPT 4o和Claude 3.5 Sonnet",
                    desc:"https://chat100.ai/zh-CN/app",
                    url:"https://chat100.ai/zh-CN/app",
                    image:"https://favicon.im/chat100.ai/zh-CN/app"
                },
                                {
                    title:"懂技术公众号自动化",
                    desc:"https://flowus.cn/ajin/d07cd84f-959b-40d8-8483-e3c83ae5d052#c0a61824-29be-4220-bfb9-85cb1eb06177",
                    url:"https://flowus.cn/ajin/d07cd84f-959b-40d8-8483-e3c83ae5d052#c0a61824-29be-4220-bfb9-85cb1eb06177",
                    image:"https://favicon.im/flowus.cn/ajin/d07cd84f-959b-40d8-8483-e3c83ae5d052#c0a61824-29be-4220-bfb9-85cb1eb06177"
                },
                                {
                    title:"免费AI文本人化器",
                    desc:"https://humanizaria.com/zh",
                    url:"https://humanizaria.com/zh",
                    image:"https://favicon.im/humanizaria.com/zh"
                },
                                {
                    title:"小红书引导微信图生成器 | 抱走大柠檬",
                    desc:"https://www.huglemon.com/tools/xhs",
                    url:"https://www.huglemon.com/tools/xhs",
                    image:"https://favicon.im/www.huglemon.com/tools/xhs"
                },
                                {
                    title:"小红书生成器-ChatGPT",
                    desc:"https://ai.xiaohongshu.live/",
                    url:"https://ai.xiaohongshu.live/",
                    image:"https://favicon.im/ai.xiaohongshu.live"
                },
                                {
                    title:"小红书笔记下载 - 免费去水印下载工具",
                    desc:"https://xhs-download.xiaobaoku.cc/",
                    url:"https://xhs-download.xiaobaoku.cc/",
                    image:"https://favicon.im/xhs-download.xiaobaoku.cc"
                },
                                {
                    title:"小薯条-小红书 AI 涨粉神器",
                    desc:"https://chipup.paitongai.net/",
                    url:"https://chipup.paitongai.net/",
                    image:"https://favicon.im/chipup.paitongai.net"
                }
            ]
        },
    ]
}